<?php
// This file generated by {calling} builder.php from source code! Do not change this file, change source code!
  require_once('C:\OSPanel\domains\microservice\objects\C.php');
  require_once('C:\OSPanel\domains\microservice\objects\D.php');
  require_once('C:\OSPanel\domains\microservice\objects\Event.php');
  require_once('C:\OSPanel\domains\microservice\controller\BaseController.php');
  require_once('C:\OSPanel\domains\microservice\server\DB.php');
  require_once('C:\OSPanel\domains\microservice\server\Host.php');
  require_once('C:\OSPanel\domains\microservice\server\Response.php');
  require_once('C:\OSPanel\domains\microservice\server\Task.php');

  use objects\C;
  use objects\D;
  use objects\Event;
  use controller\BaseController;
  use server\DB;
  use server\Host;
  use server\Response;
  use server\Task;
?>

<?php
// this source code stores in /source/index_source.php
    // echo A::Hello();
    // echo C::Hello();
    // echo D::Hello();

    // Allow access from only approved hosts
    if (!Host::Allowed(Host::CHECKTOKEN))
    {
        http_response_code(400); exit;
    }
    
    echo uniqid();
    echo "<br>";
    echo uniqid('', true);
    echo "<br>";


    $timestamp = '1299762201428';
    $date = date('Y-m-d H:i:s', substr($timestamp, 0, -3));
    

    $ev = new Event("Hellow", 33);
    print_r($ev);


    echo $_SERVER['REMOTE_ADDR'];

    // `page_ID` INT AUTO_INCREMENT NOT NULL,
    // `url` varchar(200) NOT NULL,
    // `title` varchar(200),
    // `content` TEXT,
    // `parent` varchar(10),
    // `privacy` varchar(1),
    // `status` varchar(1),
    // `creation` varchar(30),
    // PRIMARY KEY (`page_ID`)) 
    // CHARACTER SET utf8 COLLATE utf8mb4_general_ci
?>

