<?php
// This file generated by {calling} builder.php from source code! Do not change this file, change source code!
  require_once('C:\OSPanel\domains\microservice\objects\A.php');
  require_once('C:\OSPanel\domains\microservice\objects\C.php');
  require_once('C:\OSPanel\domains\microservice\objects\D.php');
  require_once('C:\OSPanel\domains\microservice\controller\BaseController.php');
  require_once('C:\OSPanel\domains\microservice\server\DB.php');
  require_once('C:\OSPanel\domains\microservice\server\Host.php');
  require_once('C:\OSPanel\domains\microservice\server\Response.php');
  require_once('C:\OSPanel\domains\microservice\server\Task.php');

  use objects\A;
  use objects\C;
  use objects\D;
  use controller\BaseController;
  use server\DB;
  use server\Host;
  use server\Response;
  use server\Task;
?>

<?php
// this source code stores in /source/index_source.php
    // echo A::Hello();
    // echo C::Hello();
    // echo D::Hello();

    // Allow access from only approved hosts
    if (!Host::Allowed(Host::CHECKTOKEN))
    {
        http_response_code(400); exit;
    }
    
    



    
    $a = new A;
    $a->Get("Vason");

    $a = new A;
    $a->Get("Vason");

    echo $_SERVER['REMOTE_ADDR'];
?>